### ISSUE TITLE
Thunder 1.0.0 with Bolt fails on a large dataset

### ISSUE THREAD

**Issue by boazmohar** [bolt-project/bolt#81] opened 2016-02-05 20:55 UTC
In Thunder 0.6 the default reduce was treeReduce (see stats function in rdds\data.py).
This enabled us to use mean on a volume of 100x1024x1024.
In Thunder 1.0.0 using Bolt this now fails:
```python
data = thunder.images.fromrandom((100,1024,1024,100), engine=sc, npartitions=100)
data.mean()
```

**Comment by freeman-lab** [comment] 2016-02-13 06:50
Fixed in https://github.com/bolt-project/bolt/commit/80e64bd7510b042a70a5b2cf7d43ebbd8ab52af0

**Comment by freeman-lab** [comment] 2016-02-13 06:51
but would be good to confirm the restored performance cc @boazmohar @sofroniewn

**Comment by boazmohar** [comment] 2016-02-14 13:08
It is working better for me, I am not sure it is at the same level as 0.6.
I always had some failed stages in the treeReduce stage in 0.6, but it recovered and completed the job.
Now it is doing something similar but I have a stage that is a retry that doesn't ever complete. It's Job is done but the stage is still active and pressing kill from the GUI doesn't do anything.
I can work with it, but I can send you an example notebook if you want.
I am using spark 2.0, i will try to check it with 1.5.1 later.

Boaz

**Comment by freeman-lab** [comment] 2016-02-14 18:06
@boazmohar thanks for the update! My first guess is it's a 1.5.1 vs 2.0.0 difference, because with this change, the implementation now should be more or less identical to what it was.

@jwittenbach mind trying to independently confirm whether there's been a performance regression here?

**Comment by boazmohar** [comment] 2016-02-14 22:57
There is a 1.5.1 vs 2.0 and 1.6 difference. 
Both later versions have more failures but 1.5.1 has some as well. I haven't seen a stage getting stuck on 1.5.1. 
I don't know if my workflow is very good for testing that as it doesn't always fail with 1.5.1, and fails differently with repeated runs on 1.6 or 2.0

**Comment by jwittenbach** [comment] 2016-02-15 15:01
I might be missing something -- but I think Spark 1.6.0 is the most recent version, correct? I'll test for speed differences between Spark 1.5.1 an 1.6.0.

**Comment by jwittenbach** [comment] 2016-02-15 15:39
First result:
I ran the following code on 10 nodes using Spark 1.5 and the latest Thunder and Bolt code.
```
data = thunder.images.fromrandom((100,1024,1024,100), engine=sc, npartitions=100)
data.values.reduce(lambda x, y: x+y)
```
I timed the second line, and it took 11 minutes -- which seems pretty slow -- though it did run to completion with no failed stages.

**Closed** 2016-05-18 21:32 UTC
